//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.example.schema.s1685_2022;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="addressSpace" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroup"/>
 *                   <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}blockSize"/>
 *                   <element name="segments" minOccurs="0">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="segment" maxOccurs="unbounded">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     <sequence>
 *                                       <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroup"/>
 *                                       <element name="addressOffset" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedLongintExpression"/>
 *                                       <element name="range" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedPositiveLongintExpression"/>
 *                                       <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
 *                                     </sequence>
 *                                     <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *                                   </restriction>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}addressUnitBits" minOccurs="0"/>
 *                   <element name="localMemoryMap" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}localMemoryMapType" minOccurs="0"/>
 *                   <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}parameters" minOccurs="0"/>
 *                   <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
 *                 </sequence>
 *                 <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addressSpace"
})
@XmlRootElement(name = "addressSpaces")
public class AddressSpaces {

    /**
     * This defines a logical space, referenced by a bus initiator.
     * 
     */
    @XmlElement(required = true)
    protected List<AddressSpaces.AddressSpace> addressSpace;

    /**
     * This defines a logical space, referenced by a bus initiator.
     * 
     * Gets the value of the addressSpace property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressSpace property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAddressSpace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressSpaces.AddressSpace }
     * </p>
     * 
     * 
     * @return
     *     The value of the addressSpace property.
     */
    public List<AddressSpaces.AddressSpace> getAddressSpace() {
        if (addressSpace == null) {
            addressSpace = new ArrayList<>();
        }
        return this.addressSpace;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroup"/>
     *         <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}blockSize"/>
     *         <element name="segments" minOccurs="0">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="segment" maxOccurs="unbounded">
     *                     <complexType>
     *                       <complexContent>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           <sequence>
     *                             <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroup"/>
     *                             <element name="addressOffset" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedLongintExpression"/>
     *                             <element name="range" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedPositiveLongintExpression"/>
     *                             <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
     *                           </sequence>
     *                           <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
     *                         </restriction>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}addressUnitBits" minOccurs="0"/>
     *         <element name="localMemoryMap" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}localMemoryMapType" minOccurs="0"/>
     *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}parameters" minOccurs="0"/>
     *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
     *       </sequence>
     *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "displayName",
        "shortDescription",
        "description",
        "range",
        "width",
        "segments",
        "addressUnitBits",
        "localMemoryMap",
        "parameters",
        "vendorExtensions"
    })
    public static class AddressSpace {

        /**
         * Unique name
         * 
         */
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "Name")
        protected String name;
        /**
         * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
         * 
         */
        protected String displayName;
        /**
         * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
         * 
         */
        protected String shortDescription;
        /**
         * Full description string, typically for documentation
         * 
         */
        protected String description;
        /**
         * The address range of an address block.  Expressed as the number of addressable units accessible to the block. The range and the width are related by the following formulas:
         * 					number_of_bits_in_block = ipxact:addressUnitBits * ipxact:range
         * 					number_of_rows_in_block = number_of_bits_in_block / ipxact:width
         * 
         */
        @XmlElement(required = true)
        protected UnsignedPositiveLongintExpression range;
        /**
         * The bit width of a row in the address block. The range and the width are related by the following formulas:
         * 					number_of_bits_in_block = ipxact:addressUnitBits * ipxact:range
         * 					number_of_rows_in_block = number_of_bits_in_block / ipxact:width
         * 
         */
        @XmlElement(required = true)
        protected UnsignedPositiveIntExpression width;
        /**
         * Address segments withing an addressSpace
         * 
         */
        protected AddressSpaces.AddressSpace.Segments segments;
        /**
         * The number of data bits in an addressable unit. The default is byte addressable (8 bits).
         * 
         */
        protected UnsignedPositiveLongintExpression addressUnitBits;
        /**
         * Provides the local memory map of an address space.  Blocks in this memory map are accessable to initiator interfaces on this component that reference this address space.   They are not accessable to any external initiator interface.
         * 
         */
        protected LocalMemoryMapType localMemoryMap;
        /**
         * Data specific to this address space.
         * 
         */
        protected Parameters parameters;
        /**
         * Container for vendor specific extensions.
         * 
         */
        protected VendorExtensions vendorExtensions;
        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         */
        @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Unique name
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getName()
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayName() {
            return displayName;
        }

        /**
         * Sets the value of the displayName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getDisplayName()
         */
        public void setDisplayName(String value) {
            this.displayName = value;
        }

        /**
         * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortDescription() {
            return shortDescription;
        }

        /**
         * Sets the value of the shortDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getShortDescription()
         */
        public void setShortDescription(String value) {
            this.shortDescription = value;
        }

        /**
         * Full description string, typically for documentation
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getDescription()
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * The address range of an address block.  Expressed as the number of addressable units accessible to the block. The range and the width are related by the following formulas:
         * 					number_of_bits_in_block = ipxact:addressUnitBits * ipxact:range
         * 					number_of_rows_in_block = number_of_bits_in_block / ipxact:width
         * 
         * @return
         *     possible object is
         *     {@link UnsignedPositiveLongintExpression }
         *     
         */
        public UnsignedPositiveLongintExpression getRange() {
            return range;
        }

        /**
         * Sets the value of the range property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnsignedPositiveLongintExpression }
         *     
         * @see #getRange()
         */
        public void setRange(UnsignedPositiveLongintExpression value) {
            this.range = value;
        }

        /**
         * The bit width of a row in the address block. The range and the width are related by the following formulas:
         * 					number_of_bits_in_block = ipxact:addressUnitBits * ipxact:range
         * 					number_of_rows_in_block = number_of_bits_in_block / ipxact:width
         * 
         * @return
         *     possible object is
         *     {@link UnsignedPositiveIntExpression }
         *     
         */
        public UnsignedPositiveIntExpression getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnsignedPositiveIntExpression }
         *     
         * @see #getWidth()
         */
        public void setWidth(UnsignedPositiveIntExpression value) {
            this.width = value;
        }

        /**
         * Address segments withing an addressSpace
         * 
         * @return
         *     possible object is
         *     {@link AddressSpaces.AddressSpace.Segments }
         *     
         */
        public AddressSpaces.AddressSpace.Segments getSegments() {
            return segments;
        }

        /**
         * Sets the value of the segments property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressSpaces.AddressSpace.Segments }
         *     
         * @see #getSegments()
         */
        public void setSegments(AddressSpaces.AddressSpace.Segments value) {
            this.segments = value;
        }

        /**
         * The number of data bits in an addressable unit. The default is byte addressable (8 bits).
         * 
         * @return
         *     possible object is
         *     {@link UnsignedPositiveLongintExpression }
         *     
         */
        public UnsignedPositiveLongintExpression getAddressUnitBits() {
            return addressUnitBits;
        }

        /**
         * Sets the value of the addressUnitBits property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnsignedPositiveLongintExpression }
         *     
         * @see #getAddressUnitBits()
         */
        public void setAddressUnitBits(UnsignedPositiveLongintExpression value) {
            this.addressUnitBits = value;
        }

        /**
         * Provides the local memory map of an address space.  Blocks in this memory map are accessable to initiator interfaces on this component that reference this address space.   They are not accessable to any external initiator interface.
         * 
         * @return
         *     possible object is
         *     {@link LocalMemoryMapType }
         *     
         */
        public LocalMemoryMapType getLocalMemoryMap() {
            return localMemoryMap;
        }

        /**
         * Sets the value of the localMemoryMap property.
         * 
         * @param value
         *     allowed object is
         *     {@link LocalMemoryMapType }
         *     
         * @see #getLocalMemoryMap()
         */
        public void setLocalMemoryMap(LocalMemoryMapType value) {
            this.localMemoryMap = value;
        }

        /**
         * Data specific to this address space.
         * 
         * @return
         *     possible object is
         *     {@link Parameters }
         *     
         */
        public Parameters getParameters() {
            return parameters;
        }

        /**
         * Sets the value of the parameters property.
         * 
         * @param value
         *     allowed object is
         *     {@link Parameters }
         *     
         * @see #getParameters()
         */
        public void setParameters(Parameters value) {
            this.parameters = value;
        }

        /**
         * Container for vendor specific extensions.
         * 
         * @return
         *     possible object is
         *     {@link VendorExtensions }
         *     
         */
        public VendorExtensions getVendorExtensions() {
            return vendorExtensions;
        }

        /**
         * Sets the value of the vendorExtensions property.
         * 
         * @param value
         *     allowed object is
         *     {@link VendorExtensions }
         *     
         * @see #getVendorExtensions()
         */
        public void setVendorExtensions(VendorExtensions value) {
            this.vendorExtensions = value;
        }

        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getId()
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="segment" maxOccurs="unbounded">
         *           <complexType>
         *             <complexContent>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 <sequence>
         *                   <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroup"/>
         *                   <element name="addressOffset" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedLongintExpression"/>
         *                   <element name="range" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedPositiveLongintExpression"/>
         *                   <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
         *                 </sequence>
         *                 <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
         *               </restriction>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "segment"
        })
        public static class Segments {

            /**
             * Address segment withing an addressSpace
             * 
             */
            @XmlElement(required = true)
            protected List<AddressSpaces.AddressSpace.Segments.Segment> segment;

            /**
             * Address segment withing an addressSpace
             * 
             * Gets the value of the segment property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the segment property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getSegment().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AddressSpaces.AddressSpace.Segments.Segment }
             * </p>
             * 
             * 
             * @return
             *     The value of the segment property.
             */
            public List<AddressSpaces.AddressSpace.Segments.Segment> getSegment() {
                if (segment == null) {
                    segment = new ArrayList<>();
                }
                return this.segment;
            }


            /**
             * <p>Java class for anonymous complex type</p>.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.</p>
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       <sequence>
             *         <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroup"/>
             *         <element name="addressOffset" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedLongintExpression"/>
             *         <element name="range" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedPositiveLongintExpression"/>
             *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
             *       </sequence>
             *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "displayName",
                "shortDescription",
                "description",
                "addressOffset",
                "range",
                "vendorExtensions"
            })
            public static class Segment {

                /**
                 * Unique name
                 * 
                 */
                @XmlElement(required = true)
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "Name")
                protected String name;
                /**
                 * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
                 * 
                 */
                protected String displayName;
                /**
                 * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
                 * 
                 */
                protected String shortDescription;
                /**
                 * Full description string, typically for documentation
                 * 
                 */
                protected String description;
                /**
                 * Address offset of the segment within the containing address space.
                 * 
                 */
                @XmlElement(required = true)
                protected UnsignedLongintExpression addressOffset;
                /**
                 * The address range of asegment.  Expressed as the number of addressable units accessible to the segment.
                 * 
                 */
                @XmlElement(required = true)
                protected UnsignedPositiveLongintExpression range;
                /**
                 * Container for vendor specific extensions.
                 * 
                 */
                protected VendorExtensions vendorExtensions;
                /**
                 * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
                 * 
                 */
                @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlID
                @XmlSchemaType(name = "ID")
                protected String id;

                /**
                 * Unique name
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 * @see #getName()
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDisplayName() {
                    return displayName;
                }

                /**
                 * Sets the value of the displayName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 * @see #getDisplayName()
                 */
                public void setDisplayName(String value) {
                    this.displayName = value;
                }

                /**
                 * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShortDescription() {
                    return shortDescription;
                }

                /**
                 * Sets the value of the shortDescription property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 * @see #getShortDescription()
                 */
                public void setShortDescription(String value) {
                    this.shortDescription = value;
                }

                /**
                 * Full description string, typically for documentation
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 * @see #getDescription()
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Address offset of the segment within the containing address space.
                 * 
                 * @return
                 *     possible object is
                 *     {@link UnsignedLongintExpression }
                 *     
                 */
                public UnsignedLongintExpression getAddressOffset() {
                    return addressOffset;
                }

                /**
                 * Sets the value of the addressOffset property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link UnsignedLongintExpression }
                 *     
                 * @see #getAddressOffset()
                 */
                public void setAddressOffset(UnsignedLongintExpression value) {
                    this.addressOffset = value;
                }

                /**
                 * The address range of asegment.  Expressed as the number of addressable units accessible to the segment.
                 * 
                 * @return
                 *     possible object is
                 *     {@link UnsignedPositiveLongintExpression }
                 *     
                 */
                public UnsignedPositiveLongintExpression getRange() {
                    return range;
                }

                /**
                 * Sets the value of the range property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link UnsignedPositiveLongintExpression }
                 *     
                 * @see #getRange()
                 */
                public void setRange(UnsignedPositiveLongintExpression value) {
                    this.range = value;
                }

                /**
                 * Container for vendor specific extensions.
                 * 
                 * @return
                 *     possible object is
                 *     {@link VendorExtensions }
                 *     
                 */
                public VendorExtensions getVendorExtensions() {
                    return vendorExtensions;
                }

                /**
                 * Sets the value of the vendorExtensions property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link VendorExtensions }
                 *     
                 * @see #getVendorExtensions()
                 */
                public void setVendorExtensions(VendorExtensions value) {
                    this.vendorExtensions = value;
                }

                /**
                 * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 * @see #getId()
                 */
                public void setId(String value) {
                    this.id = value;
                }

            }

        }

    }

}
