//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.example.schema.s1685_2022;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroupPort"/>
 *         <element name="tiedValue" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}complexTiedValueExpression" minOccurs="0"/>
 *         <element name="portReferences">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <sequence>
 *                     <element name="internalPortReference" maxOccurs="unbounded">
 *                       <complexType>
 *                         <complexContent>
 *                           <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             <sequence>
 *                               <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}subPortReference" maxOccurs="unbounded" minOccurs="0"/>
 *                               <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}partSelect" minOccurs="0"/>
 *                               <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
 *                             </sequence>
 *                             <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *                             <attribute name="portRef" use="required" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}portName" />
 *                             <attribute name="componentInstanceRef" use="required" type="{http://www.w3.org/2001/XMLSchema}Name" />
 *                           </restriction>
 *                         </complexContent>
 *                       </complexType>
 *                     </element>
 *                     <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}externalPortReference" maxOccurs="unbounded" minOccurs="0"/>
 *                   </sequence>
 *                   <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}externalPortReference" maxOccurs="unbounded"/>
 *                 </choice>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "displayName",
    "shortDescription",
    "description",
    "tiedValue",
    "portReferences",
    "vendorExtensions"
})
@XmlRootElement(name = "adHocConnection")
public class AdHocConnection {

    /**
     * Unique name
     * 
     */
    @XmlElement(required = true)
    protected String name;
    /**
     * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
     * 
     */
    protected String displayName;
    /**
     * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
     * 
     */
    protected String shortDescription;
    /**
     * Full description string, typically for documentation
     * 
     */
    protected String description;
    /**
     * The logic value of this connection. The value can be an unsigned bit vector expression or the string values 'open' or 'default'. Only valid for ports of style wire.
     * 
     */
    protected ComplexTiedValueExpression tiedValue;
    /**
     * Liist of internal and external port references involved in the adhocConnection
     * 
     */
    @XmlElement(required = true)
    protected AdHocConnection.PortReferences portReferences;
    /**
     * Container for vendor specific extensions.
     * 
     */
    protected VendorExtensions vendorExtensions;
    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     */
    @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Unique name
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getName()
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDisplayName()
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getShortDescription()
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Full description string, typically for documentation
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDescription()
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * The logic value of this connection. The value can be an unsigned bit vector expression or the string values 'open' or 'default'. Only valid for ports of style wire.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTiedValueExpression }
     *     
     */
    public ComplexTiedValueExpression getTiedValue() {
        return tiedValue;
    }

    /**
     * Sets the value of the tiedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTiedValueExpression }
     *     
     * @see #getTiedValue()
     */
    public void setTiedValue(ComplexTiedValueExpression value) {
        this.tiedValue = value;
    }

    /**
     * Liist of internal and external port references involved in the adhocConnection
     * 
     * @return
     *     possible object is
     *     {@link AdHocConnection.PortReferences }
     *     
     */
    public AdHocConnection.PortReferences getPortReferences() {
        return portReferences;
    }

    /**
     * Sets the value of the portReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdHocConnection.PortReferences }
     *     
     * @see #getPortReferences()
     */
    public void setPortReferences(AdHocConnection.PortReferences value) {
        this.portReferences = value;
    }

    /**
     * Container for vendor specific extensions.
     * 
     * @return
     *     possible object is
     *     {@link VendorExtensions }
     *     
     */
    public VendorExtensions getVendorExtensions() {
        return vendorExtensions;
    }

    /**
     * Sets the value of the vendorExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorExtensions }
     *     
     * @see #getVendorExtensions()
     */
    public void setVendorExtensions(VendorExtensions value) {
        this.vendorExtensions = value;
    }

    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getId()
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <sequence>
     *           <element name="internalPortReference" maxOccurs="unbounded">
     *             <complexType>
     *               <complexContent>
     *                 <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   <sequence>
     *                     <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}subPortReference" maxOccurs="unbounded" minOccurs="0"/>
     *                     <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}partSelect" minOccurs="0"/>
     *                     <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
     *                   </sequence>
     *                   <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
     *                   <attribute name="portRef" use="required" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}portName" />
     *                   <attribute name="componentInstanceRef" use="required" type="{http://www.w3.org/2001/XMLSchema}Name" />
     *                 </restriction>
     *               </complexContent>
     *             </complexType>
     *           </element>
     *           <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}externalPortReference" maxOccurs="unbounded" minOccurs="0"/>
     *         </sequence>
     *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}externalPortReference" maxOccurs="unbounded"/>
     *       </choice>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class PortReferences {

        /**
         * Gets the rest of the content model. 
         * 
         * <p>
         * You are getting this "catch-all" property because of the following reason: 
         * The field name "ExternalPortReference" is used by two different parts of a schema. See: 
         * line 158 of file:/Users/beribeli/Downloads/ipxact_schema_files/1685-2022/subInstances.xsd
         * line 156 of file:/Users/beribeli/Downloads/ipxact_schema_files/1685-2022/subInstances.xsd
         * <p>
         * To get rid of this property, apply a property customization to one 
         * of both of the following declarations to change their names:
         * 
         */
        @XmlElementRefs({
            @XmlElementRef(name = "internalPortReference", namespace = "http://www.accellera.org/XMLSchema/IPXACT/1685-2022", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "externalPortReference", namespace = "http://www.accellera.org/XMLSchema/IPXACT/1685-2022", type = ExternalPortReference.class, required = false)
        })
        protected List<Object> content;

        /**
         * Gets the rest of the content model. 
         * 
         * <p>
         * You are getting this "catch-all" property because of the following reason: 
         * The field name "ExternalPortReference" is used by two different parts of a schema. See: 
         * line 158 of file:/Users/beribeli/Downloads/ipxact_schema_files/1685-2022/subInstances.xsd
         * line 156 of file:/Users/beribeli/Downloads/ipxact_schema_files/1685-2022/subInstances.xsd
         * <p>
         * To get rid of this property, apply a property customization to one 
         * of both of the following declarations to change their names:
         * 
         * Gets the value of the content property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link AdHocConnection.PortReferences.InternalPortReference }{@code >}
         * {@link ExternalPortReference }
         * </p>
         * 
         * 
         * @return
         *     The value of the content property.
         */
        public List<Object> getContent() {
            if (content == null) {
                content = new ArrayList<>();
            }
            return this.content;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}subPortReference" maxOccurs="unbounded" minOccurs="0"/>
         *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}partSelect" minOccurs="0"/>
         *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
         *       </sequence>
         *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
         *       <attribute name="portRef" use="required" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}portName" />
         *       <attribute name="componentInstanceRef" use="required" type="{http://www.w3.org/2001/XMLSchema}Name" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "subPortReference",
            "partSelect",
            "vendorExtensions"
        })
        public static class InternalPortReference {

            protected List<SubPortReference> subPortReference;
            /**
             * Bit range definition.
             * 
             */
            protected PartSelect partSelect;
            /**
             * Container for vendor specific extensions.
             * 
             */
            protected VendorExtensions vendorExtensions;
            /**
             * A port on the on the referenced component from componentInterfaceRef.
             * 
             */
            @XmlAttribute(name = "portRef", required = true)
            protected String portRef;
            /**
             * A reference to the instanceName element of a component in this design.
             * 
             */
            @XmlAttribute(name = "componentInstanceRef", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "Name")
            protected String componentInstanceRef;
            /**
             * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
             * 
             */
            @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;

            /**
             * Gets the value of the subPortReference property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the subPortReference property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getSubPortReference().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SubPortReference }
             * </p>
             * 
             * 
             * @return
             *     The value of the subPortReference property.
             */
            public List<SubPortReference> getSubPortReference() {
                if (subPortReference == null) {
                    subPortReference = new ArrayList<>();
                }
                return this.subPortReference;
            }

            /**
             * Bit range definition.
             * 
             * @return
             *     possible object is
             *     {@link PartSelect }
             *     
             */
            public PartSelect getPartSelect() {
                return partSelect;
            }

            /**
             * Sets the value of the partSelect property.
             * 
             * @param value
             *     allowed object is
             *     {@link PartSelect }
             *     
             * @see #getPartSelect()
             */
            public void setPartSelect(PartSelect value) {
                this.partSelect = value;
            }

            /**
             * Container for vendor specific extensions.
             * 
             * @return
             *     possible object is
             *     {@link VendorExtensions }
             *     
             */
            public VendorExtensions getVendorExtensions() {
                return vendorExtensions;
            }

            /**
             * Sets the value of the vendorExtensions property.
             * 
             * @param value
             *     allowed object is
             *     {@link VendorExtensions }
             *     
             * @see #getVendorExtensions()
             */
            public void setVendorExtensions(VendorExtensions value) {
                this.vendorExtensions = value;
            }

            /**
             * A port on the on the referenced component from componentInterfaceRef.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPortRef() {
                return portRef;
            }

            /**
             * Sets the value of the portRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPortRef()
             */
            public void setPortRef(String value) {
                this.portRef = value;
            }

            /**
             * A reference to the instanceName element of a component in this design.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComponentInstanceRef() {
                return componentInstanceRef;
            }

            /**
             * Sets the value of the componentInstanceRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getComponentInstanceRef()
             */
            public void setComponentInstanceRef(String value) {
                this.componentInstanceRef = value;
            }

            /**
             * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getId()
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
