//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.example.schema.s1685_2022;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="enumerationDefinition" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroup"/>
 *                   <element name="width" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedPositiveIntExpression"/>
 *                   <element name="enumeratedValue" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}enumeratedValueType" maxOccurs="unbounded"/>
 *                   <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
 *                 </sequence>
 *                 <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enumerationDefinition"
})
@XmlRootElement(name = "enumerationDefinitions")
public class EnumerationDefinitions {

    @XmlElement(required = true)
    protected List<EnumerationDefinitions.EnumerationDefinition> enumerationDefinition;

    /**
     * Gets the value of the enumerationDefinition property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enumerationDefinition property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getEnumerationDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnumerationDefinitions.EnumerationDefinition }
     * </p>
     * 
     * 
     * @return
     *     The value of the enumerationDefinition property.
     */
    public List<EnumerationDefinitions.EnumerationDefinition> getEnumerationDefinition() {
        if (enumerationDefinition == null) {
            enumerationDefinition = new ArrayList<>();
        }
        return this.enumerationDefinition;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroup"/>
     *         <element name="width" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedPositiveIntExpression"/>
     *         <element name="enumeratedValue" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}enumeratedValueType" maxOccurs="unbounded"/>
     *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
     *       </sequence>
     *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "displayName",
        "shortDescription",
        "description",
        "width",
        "enumeratedValue",
        "vendorExtensions"
    })
    public static class EnumerationDefinition {

        /**
         * Unique name
         * 
         */
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "Name")
        protected String name;
        /**
         * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
         * 
         */
        protected String displayName;
        /**
         * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
         * 
         */
        protected String shortDescription;
        /**
         * Full description string, typically for documentation
         * 
         */
        protected String description;
        /**
         * Definition width used to resolve the value.
         * 
         */
        @XmlElement(required = true)
        protected UnsignedPositiveIntExpression width;
        /**
         * Enumerates specific values that can be assigned to the bit field. The name of this enumerated value. This may be used as a token in generating code.
         * 
         */
        @XmlElement(required = true)
        protected List<EnumeratedValueType> enumeratedValue;
        /**
         * Container for vendor specific extensions.
         * 
         */
        protected VendorExtensions vendorExtensions;
        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         */
        @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Unique name
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getName()
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayName() {
            return displayName;
        }

        /**
         * Sets the value of the displayName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getDisplayName()
         */
        public void setDisplayName(String value) {
            this.displayName = value;
        }

        /**
         * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortDescription() {
            return shortDescription;
        }

        /**
         * Sets the value of the shortDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getShortDescription()
         */
        public void setShortDescription(String value) {
            this.shortDescription = value;
        }

        /**
         * Full description string, typically for documentation
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getDescription()
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Definition width used to resolve the value.
         * 
         * @return
         *     possible object is
         *     {@link UnsignedPositiveIntExpression }
         *     
         */
        public UnsignedPositiveIntExpression getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnsignedPositiveIntExpression }
         *     
         * @see #getWidth()
         */
        public void setWidth(UnsignedPositiveIntExpression value) {
            this.width = value;
        }

        /**
         * Enumerates specific values that can be assigned to the bit field. The name of this enumerated value. This may be used as a token in generating code.
         * 
         * Gets the value of the enumeratedValue property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the enumeratedValue property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getEnumeratedValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EnumeratedValueType }
         * </p>
         * 
         * 
         * @return
         *     The value of the enumeratedValue property.
         */
        public List<EnumeratedValueType> getEnumeratedValue() {
            if (enumeratedValue == null) {
                enumeratedValue = new ArrayList<>();
            }
            return this.enumeratedValue;
        }

        /**
         * Container for vendor specific extensions.
         * 
         * @return
         *     possible object is
         *     {@link VendorExtensions }
         *     
         */
        public VendorExtensions getVendorExtensions() {
            return vendorExtensions;
        }

        /**
         * Sets the value of the vendorExtensions property.
         * 
         * @param value
         *     allowed object is
         *     {@link VendorExtensions }
         *     
         * @see #getVendorExtensions()
         */
        public void setVendorExtensions(VendorExtensions value) {
            this.vendorExtensions = value;
        }

        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getId()
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
