//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.example.schema.s1685_2022;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Types of generators
 * 
 * <p>Java class for generatorType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="generatorType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroup"/>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}phase" minOccurs="0"/>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}parameters" minOccurs="0"/>
 *         <element name="apiType" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2022>apiType">
 *                 <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="apiService" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="SOAP"/>
 *               <enumeration value="REST"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="transportMethods" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="transportMethod">
 *                     <complexType>
 *                       <simpleContent>
 *                         <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2022>transportMethodType">
 *                           <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *                         </extension>
 *                       </simpleContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *                 <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="generatorExe" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}ipxactURI"/>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *       <attribute name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "generatorType", propOrder = {
    "name",
    "displayName",
    "shortDescription",
    "description",
    "phase",
    "parameters",
    "apiType",
    "apiService",
    "transportMethods",
    "generatorExe",
    "vendorExtensions"
})
@XmlSeeAlso({
    InstanceGeneratorType.class,
    Generator.class
})
public class GeneratorType {

    /**
     * Unique name
     * 
     */
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "Name")
    protected String name;
    /**
     * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
     * 
     */
    protected String displayName;
    /**
     * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
     * 
     */
    protected String shortDescription;
    /**
     * Full description string, typically for documentation
     * 
     */
    protected String description;
    /**
     * This is an non-negative floating point number that is used to sequence when a generator is run. The generators are run in order starting with zero. There may be multiple generators with the same phase number. In this case, the order should not matter with respect to other generators at the same phase. If no phase number is given the generator will be considered in the "last" phase and these generators will be run in the order in which they are encountered while processing generator elements.
     * 
     */
    protected RealExpression phase;
    /**
     * A collection of parameters and associated value assertions.
     * 
     */
    protected Parameters parameters;
    /**
     * Indicates the type of API used by the generator. Valid value are TGI_2009, TGI_2014_BASE, TGI_2014_EXTENDED, TGI_2022_BASE, TGI_2022_EXTENDED, and none. If this element is not present, TGI_2022_BASE is assumed. The type TGI_2009 indicates a generator using the 1685-2009 version of the TGI API. The types TGI_2014_BASE and TGI_2014_EXTENDED indicate a generator using the 1685-2014 version of the TGI API. Types TGI_2009, TGI_2014_BASE, and TGI_2014_EXTENDED are not part of the 1685-2022 version of the standard and may not be supported by Design Environments
     * 
     */
    protected GeneratorType.ApiType apiType;
    /**
     * Communication Mechanism. Can be one of SOAP or REST (defaults to SOAP)
     * 
     */
    @XmlElement(defaultValue = "SOAP")
    protected String apiService;
    protected GeneratorType.TransportMethods transportMethods;
    /**
     * The pathname to the executable file that implements the generator
     * 
     */
    @XmlElement(required = true)
    protected IpxactURI generatorExe;
    /**
     * Container for vendor specific extensions.
     * 
     */
    protected VendorExtensions vendorExtensions;
    /**
     * If this attribute is true then the generator should not be presented to the user, it may be part of a chain and has no useful meaning when invoked standalone.
     * 
     */
    @XmlAttribute(name = "hidden")
    protected Boolean hidden;
    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     */
    @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Unique name
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getName()
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDisplayName()
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getShortDescription()
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Full description string, typically for documentation
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDescription()
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * This is an non-negative floating point number that is used to sequence when a generator is run. The generators are run in order starting with zero. There may be multiple generators with the same phase number. In this case, the order should not matter with respect to other generators at the same phase. If no phase number is given the generator will be considered in the "last" phase and these generators will be run in the order in which they are encountered while processing generator elements.
     * 
     * @return
     *     possible object is
     *     {@link RealExpression }
     *     
     */
    public RealExpression getPhase() {
        return phase;
    }

    /**
     * Sets the value of the phase property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealExpression }
     *     
     * @see #getPhase()
     */
    public void setPhase(RealExpression value) {
        this.phase = value;
    }

    /**
     * A collection of parameters and associated value assertions.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     * @see #getParameters()
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * Indicates the type of API used by the generator. Valid value are TGI_2009, TGI_2014_BASE, TGI_2014_EXTENDED, TGI_2022_BASE, TGI_2022_EXTENDED, and none. If this element is not present, TGI_2022_BASE is assumed. The type TGI_2009 indicates a generator using the 1685-2009 version of the TGI API. The types TGI_2014_BASE and TGI_2014_EXTENDED indicate a generator using the 1685-2014 version of the TGI API. Types TGI_2009, TGI_2014_BASE, and TGI_2014_EXTENDED are not part of the 1685-2022 version of the standard and may not be supported by Design Environments
     * 
     * @return
     *     possible object is
     *     {@link GeneratorType.ApiType }
     *     
     */
    public GeneratorType.ApiType getApiType() {
        return apiType;
    }

    /**
     * Sets the value of the apiType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneratorType.ApiType }
     *     
     * @see #getApiType()
     */
    public void setApiType(GeneratorType.ApiType value) {
        this.apiType = value;
    }

    /**
     * Communication Mechanism. Can be one of SOAP or REST (defaults to SOAP)
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApiService() {
        return apiService;
    }

    /**
     * Sets the value of the apiService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getApiService()
     */
    public void setApiService(String value) {
        this.apiService = value;
    }

    /**
     * Gets the value of the transportMethods property.
     * 
     * @return
     *     possible object is
     *     {@link GeneratorType.TransportMethods }
     *     
     */
    public GeneratorType.TransportMethods getTransportMethods() {
        return transportMethods;
    }

    /**
     * Sets the value of the transportMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneratorType.TransportMethods }
     *     
     */
    public void setTransportMethods(GeneratorType.TransportMethods value) {
        this.transportMethods = value;
    }

    /**
     * The pathname to the executable file that implements the generator
     * 
     * @return
     *     possible object is
     *     {@link IpxactURI }
     *     
     */
    public IpxactURI getGeneratorExe() {
        return generatorExe;
    }

    /**
     * Sets the value of the generatorExe property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpxactURI }
     *     
     * @see #getGeneratorExe()
     */
    public void setGeneratorExe(IpxactURI value) {
        this.generatorExe = value;
    }

    /**
     * Container for vendor specific extensions.
     * 
     * @return
     *     possible object is
     *     {@link VendorExtensions }
     *     
     */
    public VendorExtensions getVendorExtensions() {
        return vendorExtensions;
    }

    /**
     * Sets the value of the vendorExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorExtensions }
     *     
     * @see #getVendorExtensions()
     */
    public void setVendorExtensions(VendorExtensions value) {
        this.vendorExtensions = value;
    }

    /**
     * If this attribute is true then the generator should not be presented to the user, it may be part of a chain and has no useful meaning when invoked standalone.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHidden() {
        if (hidden == null) {
            return false;
        } else {
            return hidden;
        }
    }

    /**
     * Sets the value of the hidden property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isHidden()
     */
    public void setHidden(Boolean value) {
        this.hidden = value;
    }

    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getId()
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2022>apiType">
     *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ApiType {

        @XmlValue
        protected org.example.schema.s1685_2022.ApiType value;
        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         */
        @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link org.example.schema.s1685_2022.ApiType }
         *     
         */
        public org.example.schema.s1685_2022.ApiType getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link org.example.schema.s1685_2022.ApiType }
         *     
         */
        public void setValue(org.example.schema.s1685_2022.ApiType value) {
            this.value = value;
        }

        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getId()
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="transportMethod">
     *           <complexType>
     *             <simpleContent>
     *               <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2022>transportMethodType">
     *                 <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
     *               </extension>
     *             </simpleContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transportMethod"
    })
    public static class TransportMethods {

        /**
         * Defines a SOAP transport protocol other than HTTP which is supported by this generator. The only other currently supported protocol is 'file'.
         * 
         */
        @XmlElement(required = true)
        protected GeneratorType.TransportMethods.TransportMethod transportMethod;
        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         */
        @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Defines a SOAP transport protocol other than HTTP which is supported by this generator. The only other currently supported protocol is 'file'.
         * 
         * @return
         *     possible object is
         *     {@link GeneratorType.TransportMethods.TransportMethod }
         *     
         */
        public GeneratorType.TransportMethods.TransportMethod getTransportMethod() {
            return transportMethod;
        }

        /**
         * Sets the value of the transportMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link GeneratorType.TransportMethods.TransportMethod }
         *     
         * @see #getTransportMethod()
         */
        public void setTransportMethod(GeneratorType.TransportMethods.TransportMethod value) {
            this.transportMethod = value;
        }

        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getId()
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <simpleContent>
         *     <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2022>transportMethodType">
         *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
         *     </extension>
         *   </simpleContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class TransportMethod {

            @XmlValue
            protected TransportMethodType value;
            /**
             * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
             * 
             */
            @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link TransportMethodType }
             *     
             */
            public TransportMethodType getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link TransportMethodType }
             *     
             */
            public void setValue(TransportMethodType value) {
                this.value = value;
            }

            /**
             * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getId()
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
