excel_name = "demo.xlsx"
vendor_sheet = "version"
address_sheet = "address_map"
xml_name = "example.xml"

[xml_header]
root_tag = "component"
schema_location = "http://www.accellera.org/XMLSchema/IPXACT/1685-2014 http://www.accellera.org/XMLSchema/IPXACT/1685-2014/index.xsd"
default_ns_prefix = "ipxact"

[xml_header.ns_map]
ipxact = "http://www.accellera.org/XMLSchema/IPXACT/1685-2014"
xsi = "http://www.w3.org/2001/XMLSchema-instance"

