//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ieee.ipxact.v2009;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="cellFunction">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.spiritconsortium.org/XMLSchema/SPIRIT/1685-2009>cellFunctionValueType">
 *                 <attribute ref="{http://www.spiritconsortium.org/XMLSchema/SPIRIT/1685-2009}cellStrength"/>
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="cellClass">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.spiritconsortium.org/XMLSchema/SPIRIT/1685-2009>cellClassValueType">
 *                 <attribute ref="{http://www.spiritconsortium.org/XMLSchema/SPIRIT/1685-2009}cellStrength"/>
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cellFunction",
    "cellClass"
})
@XmlRootElement(name = "cellSpecification")
public class CellSpecification {

    /**
     * Defines a technology library cell in library independent fashion, based on specification of a cell function and strength.
     * 
     */
    protected CellSpecification.CellFunction cellFunction;
    /**
     * Defines a technology library cell in library independent fashion, based on specification of a cell class and strength.
     * 
     */
    protected CellSpecification.CellClass cellClass;

    /**
     * Defines a technology library cell in library independent fashion, based on specification of a cell function and strength.
     * 
     * @return
     *     possible object is
     *     {@link CellSpecification.CellFunction }
     *     
     */
    public CellSpecification.CellFunction getCellFunction() {
        return cellFunction;
    }

    /**
     * Sets the value of the cellFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link CellSpecification.CellFunction }
     *     
     * @see #getCellFunction()
     */
    public void setCellFunction(CellSpecification.CellFunction value) {
        this.cellFunction = value;
    }

    /**
     * Defines a technology library cell in library independent fashion, based on specification of a cell class and strength.
     * 
     * @return
     *     possible object is
     *     {@link CellSpecification.CellClass }
     *     
     */
    public CellSpecification.CellClass getCellClass() {
        return cellClass;
    }

    /**
     * Sets the value of the cellClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link CellSpecification.CellClass }
     *     
     * @see #getCellClass()
     */
    public void setCellClass(CellSpecification.CellClass value) {
        this.cellClass = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.spiritconsortium.org/XMLSchema/SPIRIT/1685-2009>cellClassValueType">
     *       <attribute ref="{http://www.spiritconsortium.org/XMLSchema/SPIRIT/1685-2009}cellStrength"/>
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CellClass {

        /**
         * Indicates legal cell class values.
         * 
         */
        @XmlValue
        protected CellClassValueType value;
        /**
         * Indicates the desired strength of the specified cell.
         * 
         */
        @XmlAttribute(name = "cellStrength", namespace = "http://www.spiritconsortium.org/XMLSchema/SPIRIT/1685-2009")
        protected CellStrengthValueType cellStrength;

        /**
         * Indicates legal cell class values.
         * 
         * @return
         *     possible object is
         *     {@link CellClassValueType }
         *     
         */
        public CellClassValueType getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link CellClassValueType }
         *     
         * @see #getValue()
         */
        public void setValue(CellClassValueType value) {
            this.value = value;
        }

        /**
         * Indicates the desired strength of the specified cell.
         * 
         * @return
         *     possible object is
         *     {@link CellStrengthValueType }
         *     
         */
        public CellStrengthValueType getCellStrength() {
            return cellStrength;
        }

        /**
         * Sets the value of the cellStrength property.
         * 
         * @param value
         *     allowed object is
         *     {@link CellStrengthValueType }
         *     
         * @see #getCellStrength()
         */
        public void setCellStrength(CellStrengthValueType value) {
            this.cellStrength = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.spiritconsortium.org/XMLSchema/SPIRIT/1685-2009>cellFunctionValueType">
     *       <attribute ref="{http://www.spiritconsortium.org/XMLSchema/SPIRIT/1685-2009}cellStrength"/>
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CellFunction {

        /**
         * Indicates legal cell function values.
         * 
         */
        @XmlValue
        protected CellFunctionValueType value;
        /**
         * Indicates the desired strength of the specified cell.
         * 
         */
        @XmlAttribute(name = "cellStrength", namespace = "http://www.spiritconsortium.org/XMLSchema/SPIRIT/1685-2009")
        protected CellStrengthValueType cellStrength;

        /**
         * Indicates legal cell function values.
         * 
         * @return
         *     possible object is
         *     {@link CellFunctionValueType }
         *     
         */
        public CellFunctionValueType getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link CellFunctionValueType }
         *     
         * @see #getValue()
         */
        public void setValue(CellFunctionValueType value) {
            this.value = value;
        }

        /**
         * Indicates the desired strength of the specified cell.
         * 
         * @return
         *     possible object is
         *     {@link CellStrengthValueType }
         *     
         */
        public CellStrengthValueType getCellStrength() {
            return cellStrength;
        }

        /**
         * Sets the value of the cellStrength property.
         * 
         * @param value
         *     allowed object is
         *     {@link CellStrengthValueType }
         *     
         * @see #getCellStrength()
         */
        public void setCellStrength(CellStrengthValueType value) {
            this.cellStrength = value;
        }

    }

}
