//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.example.schema.s1685_2014;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Model information for an abstractor.
 * 
 * <p>Java class for abstractorModelType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="abstractorModelType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="views" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="view" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}nameGroupNMTOKEN"/>
 *                             <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}isPresent" minOccurs="0"/>
 *                             <element name="envIdentifier" maxOccurs="unbounded" minOccurs="0">
 *                               <complexType>
 *                                 <simpleContent>
 *                                   <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2014>envIdentifierType">
 *                                     <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}id.att"/>
 *                                   </extension>
 *                                 </simpleContent>
 *                               </complexType>
 *                             </element>
 *                             <element name="componentInstantiationRef" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="instantiations" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="componentInstantiation" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}componentInstantiationType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="ports" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="port" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}abstractorPortType" maxOccurs="unbounded" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstractorModelType", propOrder = {
    "views",
    "instantiations",
    "ports"
})
public class AbstractorModelType {

    /**
     * Views container
     * 
     */
    protected AbstractorModelType.Views views;
    /**
     * Instantiations container
     * 
     */
    protected AbstractorModelType.Instantiations instantiations;
    /**
     * Port container
     * 
     */
    protected AbstractorModelType.Ports ports;

    /**
     * Views container
     * 
     * @return
     *     possible object is
     *     {@link AbstractorModelType.Views }
     *     
     */
    public AbstractorModelType.Views getViews() {
        return views;
    }

    /**
     * Sets the value of the views property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractorModelType.Views }
     *     
     * @see #getViews()
     */
    public void setViews(AbstractorModelType.Views value) {
        this.views = value;
    }

    /**
     * Instantiations container
     * 
     * @return
     *     possible object is
     *     {@link AbstractorModelType.Instantiations }
     *     
     */
    public AbstractorModelType.Instantiations getInstantiations() {
        return instantiations;
    }

    /**
     * Sets the value of the instantiations property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractorModelType.Instantiations }
     *     
     * @see #getInstantiations()
     */
    public void setInstantiations(AbstractorModelType.Instantiations value) {
        this.instantiations = value;
    }

    /**
     * Port container
     * 
     * @return
     *     possible object is
     *     {@link AbstractorModelType.Ports }
     *     
     */
    public AbstractorModelType.Ports getPorts() {
        return ports;
    }

    /**
     * Sets the value of the ports property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractorModelType.Ports }
     *     
     * @see #getPorts()
     */
    public void setPorts(AbstractorModelType.Ports value) {
        this.ports = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="componentInstantiation" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}componentInstantiationType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "componentInstantiation"
    })
    public static class Instantiations {

        /**
         * Component Instantiation
         * 
         */
        @XmlElement(required = true)
        protected List<ComponentInstantiationType> componentInstantiation;

        /**
         * Component Instantiation
         * 
         * Gets the value of the componentInstantiation property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the componentInstantiation property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getComponentInstantiation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ComponentInstantiationType }
         * </p>
         * 
         * 
         * @return
         *     The value of the componentInstantiation property.
         */
        public List<ComponentInstantiationType> getComponentInstantiation() {
            if (componentInstantiation == null) {
                componentInstantiation = new ArrayList<>();
            }
            return this.componentInstantiation;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="port" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}abstractorPortType" maxOccurs="unbounded" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "port"
    })
    public static class Ports {

        protected List<AbstractorPortType> port;

        /**
         * Gets the value of the port property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the port property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getPort().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AbstractorPortType }
         * </p>
         * 
         * 
         * @return
         *     The value of the port property.
         */
        public List<AbstractorPortType> getPort() {
            if (port == null) {
                port = new ArrayList<>();
            }
            return this.port;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="view" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}nameGroupNMTOKEN"/>
     *                   <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}isPresent" minOccurs="0"/>
     *                   <element name="envIdentifier" maxOccurs="unbounded" minOccurs="0">
     *                     <complexType>
     *                       <simpleContent>
     *                         <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2014>envIdentifierType">
     *                           <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}id.att"/>
     *                         </extension>
     *                       </simpleContent>
     *                     </complexType>
     *                   </element>
     *                   <element name="componentInstantiationRef" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "view"
    })
    public static class Views {

        /**
         * Single view of an abstracto
         * 
         */
        @XmlElement(required = true)
        protected List<AbstractorModelType.Views.View> view;

        /**
         * Single view of an abstracto
         * 
         * Gets the value of the view property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the view property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getView().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AbstractorModelType.Views.View }
         * </p>
         * 
         * 
         * @return
         *     The value of the view property.
         */
        public List<AbstractorModelType.Views.View> getView() {
            if (view == null) {
                view = new ArrayList<>();
            }
            return this.view;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}nameGroupNMTOKEN"/>
         *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}isPresent" minOccurs="0"/>
         *         <element name="envIdentifier" maxOccurs="unbounded" minOccurs="0">
         *           <complexType>
         *             <simpleContent>
         *               <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2014>envIdentifierType">
         *                 <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}id.att"/>
         *               </extension>
         *             </simpleContent>
         *           </complexType>
         *         </element>
         *         <element name="componentInstantiationRef" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "displayName",
            "description",
            "isPresent",
            "envIdentifier",
            "componentInstantiationRef"
        })
        public static class View {

            /**
             * Unique name
             * 
             */
            @XmlElement(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String name;
            /**
             * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
             * 
             */
            protected String displayName;
            /**
             * Full description string, typically for documentation
             * 
             */
            protected String description;
            /**
             * Expression that determines whether the enclosing element should be treated as present (expression evaluates to "true") or disregarded (expression evalutes to "false")
             * 
             */
            protected UnsignedBitExpression isPresent;
            /**
             * Defines the hardware environment in which this view applies. The format of the string is language:tool:vendor_extension, with each piece being optional. The language must be one of the types from ipxact:fileType. The tool values are defined by the Accellera Systems Initiative, and include generic values "*Simulation" and "*Synthesis" to imply any tool of the indicated type. Having more than one envIdentifier indicates that the view applies to multiple environments.
             * 
             */
            protected List<AbstractorModelType.Views.View.EnvIdentifier> envIdentifier;
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String componentInstantiationRef;

            /**
             * Unique name
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getName()
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisplayName() {
                return displayName;
            }

            /**
             * Sets the value of the displayName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getDisplayName()
             */
            public void setDisplayName(String value) {
                this.displayName = value;
            }

            /**
             * Full description string, typically for documentation
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getDescription()
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Expression that determines whether the enclosing element should be treated as present (expression evaluates to "true") or disregarded (expression evalutes to "false")
             * 
             * @return
             *     possible object is
             *     {@link UnsignedBitExpression }
             *     
             */
            public UnsignedBitExpression getIsPresent() {
                return isPresent;
            }

            /**
             * Sets the value of the isPresent property.
             * 
             * @param value
             *     allowed object is
             *     {@link UnsignedBitExpression }
             *     
             * @see #getIsPresent()
             */
            public void setIsPresent(UnsignedBitExpression value) {
                this.isPresent = value;
            }

            /**
             * Defines the hardware environment in which this view applies. The format of the string is language:tool:vendor_extension, with each piece being optional. The language must be one of the types from ipxact:fileType. The tool values are defined by the Accellera Systems Initiative, and include generic values "*Simulation" and "*Synthesis" to imply any tool of the indicated type. Having more than one envIdentifier indicates that the view applies to multiple environments.
             * 
             * Gets the value of the envIdentifier property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the envIdentifier property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getEnvIdentifier().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AbstractorModelType.Views.View.EnvIdentifier }
             * </p>
             * 
             * 
             * @return
             *     The value of the envIdentifier property.
             */
            public List<AbstractorModelType.Views.View.EnvIdentifier> getEnvIdentifier() {
                if (envIdentifier == null) {
                    envIdentifier = new ArrayList<>();
                }
                return this.envIdentifier;
            }

            /**
             * Gets the value of the componentInstantiationRef property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComponentInstantiationRef() {
                return componentInstantiationRef;
            }

            /**
             * Sets the value of the componentInstantiationRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComponentInstantiationRef(String value) {
                this.componentInstantiationRef = value;
            }


            /**
             * <p>Java class for anonymous complex type</p>.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.</p>
             * 
             * <pre>{@code
             * <complexType>
             *   <simpleContent>
             *     <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2014>envIdentifierType">
             *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2014}id.att"/>
             *     </extension>
             *   </simpleContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class EnvIdentifier {

                @XmlValue
                protected String value;
                /**
                 * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
                 * 
                 */
                @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlID
                @XmlSchemaType(name = "ID")
                protected String id;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 * @see #getId()
                 */
                public void setId(String value) {
                    this.id = value;
                }

            }

        }

    }

}
