//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ieee.ipxact.v2022;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Address blocks inside a bank do not specify address.
 * 
 * <p>Java class for bankedBlockType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="bankedBlockType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroup"/>
 *         <element name="accessHandles" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence maxOccurs="unbounded">
 *                   <element name="accessHandle" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}slicedAccessHandle"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}blockSize"/>
 *         <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}addressBlockExtensions"/>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bankedBlockType", propOrder = {
    "name",
    "displayName",
    "shortDescription",
    "description",
    "accessHandles",
    "range",
    "width",
    "usage",
    "_volatile",
    "accessPolicies",
    "parameters",
    "registerData",
    "vendorExtensions"
})
public class BankedBlockType {

    /**
     * Unique name
     * 
     */
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "Name")
    protected String name;
    /**
     * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
     * 
     */
    protected String displayName;
    /**
     * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
     * 
     */
    protected String shortDescription;
    /**
     * Full description string, typically for documentation
     * 
     */
    protected String description;
    protected BankedBlockType.AccessHandles accessHandles;
    /**
     * The address range of an address block.  Expressed as the number of addressable units accessible to the block. The range and the width are related by the following formulas:
     * 					number_of_bits_in_block = ipxact:addressUnitBits * ipxact:range
     * 					number_of_rows_in_block = number_of_bits_in_block / ipxact:width
     * 
     */
    @XmlElement(required = true)
    protected UnsignedPositiveLongintExpression range;
    /**
     * The bit width of a row in the address block. The range and the width are related by the following formulas:
     * 					number_of_bits_in_block = ipxact:addressUnitBits * ipxact:range
     * 					number_of_rows_in_block = number_of_bits_in_block / ipxact:width
     * 
     */
    @XmlElement(required = true)
    protected UnsignedPositiveIntExpression width;
    /**
     * Indicates the usage of this block.  Possible values are 'memory', 'register' and 'reserved'.
     * 
     */
    @XmlSchemaType(name = "token")
    protected UsageType usage;
    /**
     * Indicates whether the data is volatile.
     * 
     */
    @XmlElement(name = "volatile")
    protected Boolean _volatile;
    protected AccessPolicies accessPolicies;
    /**
     * Any additional parameters needed to describe this address block to the generators.
     * 
     */
    protected Parameters parameters;
    /**
     * This group of optional elements describes the memory mapped registers of an address block
     * 
     */
    @XmlElements({
        @XmlElement(name = "register", type = RegisterFile.Register.class),
        @XmlElement(name = "registerFile", type = RegisterFile.class)
    })
    protected List<Object> registerData;
    /**
     * Container for vendor specific extensions.
     * 
     */
    protected VendorExtensions vendorExtensions;
    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     */
    @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Unique name
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getName()
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDisplayName()
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getShortDescription()
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Full description string, typically for documentation
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDescription()
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the accessHandles property.
     * 
     * @return
     *     possible object is
     *     {@link BankedBlockType.AccessHandles }
     *     
     */
    public BankedBlockType.AccessHandles getAccessHandles() {
        return accessHandles;
    }

    /**
     * Sets the value of the accessHandles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankedBlockType.AccessHandles }
     *     
     */
    public void setAccessHandles(BankedBlockType.AccessHandles value) {
        this.accessHandles = value;
    }

    /**
     * The address range of an address block.  Expressed as the number of addressable units accessible to the block. The range and the width are related by the following formulas:
     * 					number_of_bits_in_block = ipxact:addressUnitBits * ipxact:range
     * 					number_of_rows_in_block = number_of_bits_in_block / ipxact:width
     * 
     * @return
     *     possible object is
     *     {@link UnsignedPositiveLongintExpression }
     *     
     */
    public UnsignedPositiveLongintExpression getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedPositiveLongintExpression }
     *     
     * @see #getRange()
     */
    public void setRange(UnsignedPositiveLongintExpression value) {
        this.range = value;
    }

    /**
     * The bit width of a row in the address block. The range and the width are related by the following formulas:
     * 					number_of_bits_in_block = ipxact:addressUnitBits * ipxact:range
     * 					number_of_rows_in_block = number_of_bits_in_block / ipxact:width
     * 
     * @return
     *     possible object is
     *     {@link UnsignedPositiveIntExpression }
     *     
     */
    public UnsignedPositiveIntExpression getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedPositiveIntExpression }
     *     
     * @see #getWidth()
     */
    public void setWidth(UnsignedPositiveIntExpression value) {
        this.width = value;
    }

    /**
     * Indicates the usage of this block.  Possible values are 'memory', 'register' and 'reserved'.
     * 
     * @return
     *     possible object is
     *     {@link UsageType }
     *     
     */
    public UsageType getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsageType }
     *     
     * @see #getUsage()
     */
    public void setUsage(UsageType value) {
        this.usage = value;
    }

    /**
     * Indicates whether the data is volatile.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVolatile() {
        return _volatile;
    }

    /**
     * Sets the value of the volatile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isVolatile()
     */
    public void setVolatile(Boolean value) {
        this._volatile = value;
    }

    /**
     * Gets the value of the accessPolicies property.
     * 
     * @return
     *     possible object is
     *     {@link AccessPolicies }
     *     
     */
    public AccessPolicies getAccessPolicies() {
        return accessPolicies;
    }

    /**
     * Sets the value of the accessPolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessPolicies }
     *     
     */
    public void setAccessPolicies(AccessPolicies value) {
        this.accessPolicies = value;
    }

    /**
     * Any additional parameters needed to describe this address block to the generators.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     * @see #getParameters()
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * This group of optional elements describes the memory mapped registers of an address block
     * 
     * Gets the value of the registerData property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the registerData property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getRegisterData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegisterFile }
     * {@link RegisterFile.Register }
     * </p>
     * 
     * 
     * @return
     *     The value of the registerData property.
     */
    public List<Object> getRegisterData() {
        if (registerData == null) {
            registerData = new ArrayList<>();
        }
        return this.registerData;
    }

    /**
     * Container for vendor specific extensions.
     * 
     * @return
     *     possible object is
     *     {@link VendorExtensions }
     *     
     */
    public VendorExtensions getVendorExtensions() {
        return vendorExtensions;
    }

    /**
     * Sets the value of the vendorExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorExtensions }
     *     
     * @see #getVendorExtensions()
     */
    public void setVendorExtensions(VendorExtensions value) {
        this.vendorExtensions = value;
    }

    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getId()
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence maxOccurs="unbounded">
     *         <element name="accessHandle" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}slicedAccessHandle"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accessHandle"
    })
    public static class AccessHandles {

        @XmlElement(required = true)
        protected List<SlicedAccessHandle> accessHandle;

        /**
         * Gets the value of the accessHandle property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the accessHandle property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getAccessHandle().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SlicedAccessHandle }
         * </p>
         * 
         * 
         * @return
         *     The value of the accessHandle property.
         */
        public List<SlicedAccessHandle> getAccessHandle() {
            if (accessHandle == null) {
                accessHandle = new ArrayList<>();
            }
            return this.accessHandle;
        }

    }

}
