//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ieee.ipxact.v2022;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for clockDriverType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="clockDriverType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="clockPeriod">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2022>realExpression">
 *                 <attribute name="units" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}delayValueUnitType" default="ns" />
 *                 <anyAttribute processContents='lax' namespace='##other'/>
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="clockPulseOffset">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2022>realExpression">
 *                 <attribute name="units" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}delayValueUnitType" default="ns" />
 *                 <anyAttribute processContents='lax' namespace='##other'/>
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="clockPulseValue" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedBitExpression"/>
 *         <element name="clockPulseDuration">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2022>realExpression">
 *                 <attribute name="units" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}delayValueUnitType" default="ns" />
 *                 <anyAttribute processContents='lax' namespace='##other'/>
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "clockDriverType", propOrder = {
    "clockPeriod",
    "clockPulseOffset",
    "clockPulseValue",
    "clockPulseDuration"
})
@XmlSeeAlso({
    OtherClockDriver.class,
    ClockDriver.class
})
public class ClockDriverType {

    /**
     * Clock period in units defined by the units attribute. Default is nanoseconds.
     * 
     */
    @XmlElement(required = true)
    protected ClockDriverType.ClockPeriod clockPeriod;
    /**
     * Time until first pulse. Units are defined by the units attribute. Default is nanoseconds.
     * 
     */
    @XmlElement(required = true)
    protected ClockDriverType.ClockPulseOffset clockPulseOffset;
    /**
     * Value of port after first clock edge.
     * 
     */
    @XmlElement(required = true)
    protected UnsignedBitExpression clockPulseValue;
    /**
     * Duration of first state in cycle. Units are defined by the units attribute. Default is nanoseconds.
     * 
     */
    @XmlElement(required = true)
    protected ClockDriverType.ClockPulseDuration clockPulseDuration;
    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     */
    @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Clock period in units defined by the units attribute. Default is nanoseconds.
     * 
     * @return
     *     possible object is
     *     {@link ClockDriverType.ClockPeriod }
     *     
     */
    public ClockDriverType.ClockPeriod getClockPeriod() {
        return clockPeriod;
    }

    /**
     * Sets the value of the clockPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClockDriverType.ClockPeriod }
     *     
     * @see #getClockPeriod()
     */
    public void setClockPeriod(ClockDriverType.ClockPeriod value) {
        this.clockPeriod = value;
    }

    /**
     * Time until first pulse. Units are defined by the units attribute. Default is nanoseconds.
     * 
     * @return
     *     possible object is
     *     {@link ClockDriverType.ClockPulseOffset }
     *     
     */
    public ClockDriverType.ClockPulseOffset getClockPulseOffset() {
        return clockPulseOffset;
    }

    /**
     * Sets the value of the clockPulseOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClockDriverType.ClockPulseOffset }
     *     
     * @see #getClockPulseOffset()
     */
    public void setClockPulseOffset(ClockDriverType.ClockPulseOffset value) {
        this.clockPulseOffset = value;
    }

    /**
     * Value of port after first clock edge.
     * 
     * @return
     *     possible object is
     *     {@link UnsignedBitExpression }
     *     
     */
    public UnsignedBitExpression getClockPulseValue() {
        return clockPulseValue;
    }

    /**
     * Sets the value of the clockPulseValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedBitExpression }
     *     
     * @see #getClockPulseValue()
     */
    public void setClockPulseValue(UnsignedBitExpression value) {
        this.clockPulseValue = value;
    }

    /**
     * Duration of first state in cycle. Units are defined by the units attribute. Default is nanoseconds.
     * 
     * @return
     *     possible object is
     *     {@link ClockDriverType.ClockPulseDuration }
     *     
     */
    public ClockDriverType.ClockPulseDuration getClockPulseDuration() {
        return clockPulseDuration;
    }

    /**
     * Sets the value of the clockPulseDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClockDriverType.ClockPulseDuration }
     *     
     * @see #getClockPulseDuration()
     */
    public void setClockPulseDuration(ClockDriverType.ClockPulseDuration value) {
        this.clockPulseDuration = value;
    }

    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getId()
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2022>realExpression">
     *       <attribute name="units" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}delayValueUnitType" default="ns" />
     *       <anyAttribute processContents='lax' namespace='##other'/>
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ClockPeriod
        extends RealExpression
    {

        @XmlAttribute(name = "units")
        protected DelayValueUnitType units;

        /**
         * Gets the value of the units property.
         * 
         * @return
         *     possible object is
         *     {@link DelayValueUnitType }
         *     
         */
        public DelayValueUnitType getUnits() {
            if (units == null) {
                return DelayValueUnitType.NS;
            } else {
                return units;
            }
        }

        /**
         * Sets the value of the units property.
         * 
         * @param value
         *     allowed object is
         *     {@link DelayValueUnitType }
         *     
         */
        public void setUnits(DelayValueUnitType value) {
            this.units = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2022>realExpression">
     *       <attribute name="units" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}delayValueUnitType" default="ns" />
     *       <anyAttribute processContents='lax' namespace='##other'/>
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ClockPulseDuration
        extends RealExpression
    {

        @XmlAttribute(name = "units")
        protected DelayValueUnitType units;

        /**
         * Gets the value of the units property.
         * 
         * @return
         *     possible object is
         *     {@link DelayValueUnitType }
         *     
         */
        public DelayValueUnitType getUnits() {
            if (units == null) {
                return DelayValueUnitType.NS;
            } else {
                return units;
            }
        }

        /**
         * Sets the value of the units property.
         * 
         * @param value
         *     allowed object is
         *     {@link DelayValueUnitType }
         *     
         */
        public void setUnits(DelayValueUnitType value) {
            this.units = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.accellera.org/XMLSchema/IPXACT/1685-2022>realExpression">
     *       <attribute name="units" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}delayValueUnitType" default="ns" />
     *       <anyAttribute processContents='lax' namespace='##other'/>
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ClockPulseOffset
        extends RealExpression
    {

        @XmlAttribute(name = "units")
        protected DelayValueUnitType units;

        /**
         * Gets the value of the units property.
         * 
         * @return
         *     possible object is
         *     {@link DelayValueUnitType }
         *     
         */
        public DelayValueUnitType getUnits() {
            if (units == null) {
                return DelayValueUnitType.NS;
            } else {
                return units;
            }
        }

        /**
         * Sets the value of the units property.
         * 
         * @param value
         *     allowed object is
         *     {@link DelayValueUnitType }
         *     
         */
        public void setUnits(DelayValueUnitType value) {
            this.units = value;
        }

    }

}
