//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ieee.ipxact.v2022;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for fileSetType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="fileSetType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameGroup"/>
 *         <element name="group" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>Name">
 *                 <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}file" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="defaultFileBuilder" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}fileBuilderType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}dependency" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="function" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="entryPoint" type="{http://www.w3.org/2001/XMLSchema}Name" minOccurs="0"/>
 *                   <element name="fileRef" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *                   <element name="returnType" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}returnTypeType" minOccurs="0"/>
 *                   <element name="argument" maxOccurs="unbounded" minOccurs="0">
 *                     <complexType>
 *                       <complexContent>
 *                         <extension base="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameValuePairType">
 *                           <attribute name="dataType" use="required" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}dataTypeType" />
 *                         </extension>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="disabled" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedBitExpression" minOccurs="0"/>
 *                   <element name="sourceFile" maxOccurs="unbounded" minOccurs="0">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="sourceName" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}ipxactURI"/>
 *                             <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}fileType"/>
 *                           </sequence>
 *                           <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *                 <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *                 <attribute name="replicate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fileSetType", propOrder = {
    "name",
    "displayName",
    "shortDescription",
    "description",
    "group",
    "file",
    "defaultFileBuilder",
    "dependency",
    "function",
    "vendorExtensions"
})
public class FileSetType {

    /**
     * Unique name
     * 
     */
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "Name")
    protected String name;
    /**
     * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
     * 
     */
    protected String displayName;
    /**
     * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
     * 
     */
    protected String shortDescription;
    /**
     * Full description string, typically for documentation
     * 
     */
    protected String description;
    /**
     * Identifies this filleSet as belonging to a particular group or having a particular purpose. Examples might be "diagnostics", "boot", "application", "interrupt", "deviceDriver", etc.
     * 
     */
    protected List<FileSetType.Group> group;
    /**
     * IP-XACT reference to a file or directory.
     * 
     */
    protected List<File> file;
    /**
     * Default command and flags used to build derived files from the sourceName files in this file set.
     * 
     */
    protected List<FileBuilderType> defaultFileBuilder;
    /**
     * Specifies a location on which  files or fileSets may be dependent. Typically, this would be a directory that would contain included files.
     * 
     */
    protected List<Dependency> dependency;
    /**
     * Generator information if this file set describes a function. For example, this file set may describe diagnostics for which the DE can generate a diagnostics driver.
     * 
     */
    protected List<FileSetType.Function> function;
    /**
     * Container for vendor specific extensions.
     * 
     */
    protected VendorExtensions vendorExtensions;
    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     */
    @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Unique name
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getName()
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Element name for display purposes. Typically a few words providing a more detailed and/or user-friendly name than the ipxact:name.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDisplayName()
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Brief description suitable for titles, software comments and pop-up windows. Being a SystemVerilog expression the text can be constructed using parameters, e.g, by concatentation or $sformatf().
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getShortDescription()
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Full description string, typically for documentation
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDescription()
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Identifies this filleSet as belonging to a particular group or having a particular purpose. Examples might be "diagnostics", "boot", "application", "interrupt", "deviceDriver", etc.
     * 
     * Gets the value of the group property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the group property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileSetType.Group }
     * </p>
     * 
     * 
     * @return
     *     The value of the group property.
     */
    public List<FileSetType.Group> getGroup() {
        if (group == null) {
            group = new ArrayList<>();
        }
        return this.group;
    }

    /**
     * IP-XACT reference to a file or directory.
     * 
     * Gets the value of the file property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the file property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link File }
     * </p>
     * 
     * 
     * @return
     *     The value of the file property.
     */
    public List<File> getFile() {
        if (file == null) {
            file = new ArrayList<>();
        }
        return this.file;
    }

    /**
     * Default command and flags used to build derived files from the sourceName files in this file set.
     * 
     * Gets the value of the defaultFileBuilder property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defaultFileBuilder property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDefaultFileBuilder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileBuilderType }
     * </p>
     * 
     * 
     * @return
     *     The value of the defaultFileBuilder property.
     */
    public List<FileBuilderType> getDefaultFileBuilder() {
        if (defaultFileBuilder == null) {
            defaultFileBuilder = new ArrayList<>();
        }
        return this.defaultFileBuilder;
    }

    /**
     * Specifies a location on which  files or fileSets may be dependent. Typically, this would be a directory that would contain included files.
     * 
     * Gets the value of the dependency property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dependency property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDependency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dependency }
     * </p>
     * 
     * 
     * @return
     *     The value of the dependency property.
     */
    public List<Dependency> getDependency() {
        if (dependency == null) {
            dependency = new ArrayList<>();
        }
        return this.dependency;
    }

    /**
     * Generator information if this file set describes a function. For example, this file set may describe diagnostics for which the DE can generate a diagnostics driver.
     * 
     * Gets the value of the function property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the function property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getFunction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileSetType.Function }
     * </p>
     * 
     * 
     * @return
     *     The value of the function property.
     */
    public List<FileSetType.Function> getFunction() {
        if (function == null) {
            function = new ArrayList<>();
        }
        return this.function;
    }

    /**
     * Container for vendor specific extensions.
     * 
     * @return
     *     possible object is
     *     {@link VendorExtensions }
     *     
     */
    public VendorExtensions getVendorExtensions() {
        return vendorExtensions;
    }

    /**
     * Sets the value of the vendorExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorExtensions }
     *     
     * @see #getVendorExtensions()
     */
    public void setVendorExtensions(VendorExtensions value) {
        this.vendorExtensions = value;
    }

    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getId()
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="entryPoint" type="{http://www.w3.org/2001/XMLSchema}Name" minOccurs="0"/>
     *         <element name="fileRef" type="{http://www.w3.org/2001/XMLSchema}token"/>
     *         <element name="returnType" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}returnTypeType" minOccurs="0"/>
     *         <element name="argument" maxOccurs="unbounded" minOccurs="0">
     *           <complexType>
     *             <complexContent>
     *               <extension base="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameValuePairType">
     *                 <attribute name="dataType" use="required" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}dataTypeType" />
     *               </extension>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="disabled" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedBitExpression" minOccurs="0"/>
     *         <element name="sourceFile" maxOccurs="unbounded" minOccurs="0">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="sourceName" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}ipxactURI"/>
     *                   <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}fileType"/>
     *                 </sequence>
     *                 <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
     *       <attribute name="replicate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entryPoint",
        "fileRef",
        "returnType",
        "argument",
        "disabled",
        "sourceFile"
    })
    public static class Function {

        /**
         * Optional name for the function.
         * 
         */
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "Name")
        protected String entryPoint;
        /**
         * A reference to the file that contains the entry point function.
         * 
         */
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String fileRef;
        /**
         * Function return type. Possible values are void and int.
         * 
         */
        @XmlSchemaType(name = "string")
        protected ReturnTypeType returnType;
        /**
         * Arguments passed in when the function is called. Arguments are passed in order.
         * 
         * This is an extension of the name-value pair which includes the data type in the ipxact:dataType attribute.  The argument name is in the ipxact:name element and its value is in the ipxact:value element.
         * 
         */
        protected List<FileSetType.Function.Argument> argument;
        /**
         * Specifies if the SW function is enabled. If not present the function is always enabled.
         * 
         */
        protected UnsignedBitExpression disabled;
        /**
         * Location information for the source file of this function.
         * 
         */
        protected List<FileSetType.Function.SourceFile> sourceFile;
        /**
         * If true directs the generator to compile a separate object module for each instance of the component in the design. If false (default) the function will be called with different arguments for each instance.
         * 
         */
        @XmlAttribute(name = "replicate")
        protected Boolean replicate;
        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         */
        @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Optional name for the function.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntryPoint() {
            return entryPoint;
        }

        /**
         * Sets the value of the entryPoint property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getEntryPoint()
         */
        public void setEntryPoint(String value) {
            this.entryPoint = value;
        }

        /**
         * A reference to the file that contains the entry point function.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileRef() {
            return fileRef;
        }

        /**
         * Sets the value of the fileRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getFileRef()
         */
        public void setFileRef(String value) {
            this.fileRef = value;
        }

        /**
         * Function return type. Possible values are void and int.
         * 
         * @return
         *     possible object is
         *     {@link ReturnTypeType }
         *     
         */
        public ReturnTypeType getReturnType() {
            return returnType;
        }

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReturnTypeType }
         *     
         * @see #getReturnType()
         */
        public void setReturnType(ReturnTypeType value) {
            this.returnType = value;
        }

        /**
         * Arguments passed in when the function is called. Arguments are passed in order.
         * 
         * This is an extension of the name-value pair which includes the data type in the ipxact:dataType attribute.  The argument name is in the ipxact:name element and its value is in the ipxact:value element.
         * 
         * Gets the value of the argument property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the argument property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getArgument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FileSetType.Function.Argument }
         * </p>
         * 
         * 
         * @return
         *     The value of the argument property.
         */
        public List<FileSetType.Function.Argument> getArgument() {
            if (argument == null) {
                argument = new ArrayList<>();
            }
            return this.argument;
        }

        /**
         * Specifies if the SW function is enabled. If not present the function is always enabled.
         * 
         * @return
         *     possible object is
         *     {@link UnsignedBitExpression }
         *     
         */
        public UnsignedBitExpression getDisabled() {
            return disabled;
        }

        /**
         * Sets the value of the disabled property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnsignedBitExpression }
         *     
         * @see #getDisabled()
         */
        public void setDisabled(UnsignedBitExpression value) {
            this.disabled = value;
        }

        /**
         * Location information for the source file of this function.
         * 
         * Gets the value of the sourceFile property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sourceFile property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getSourceFile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FileSetType.Function.SourceFile }
         * </p>
         * 
         * 
         * @return
         *     The value of the sourceFile property.
         */
        public List<FileSetType.Function.SourceFile> getSourceFile() {
            if (sourceFile == null) {
                sourceFile = new ArrayList<>();
            }
            return this.sourceFile;
        }

        /**
         * If true directs the generator to compile a separate object module for each instance of the component in the design. If false (default) the function will be called with different arguments for each instance.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isReplicate() {
            if (replicate == null) {
                return false;
            } else {
                return replicate;
            }
        }

        /**
         * Sets the value of the replicate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         * @see #isReplicate()
         */
        public void setReplicate(Boolean value) {
            this.replicate = value;
        }

        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getId()
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <extension base="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}nameValuePairType">
         *       <attribute name="dataType" use="required" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}dataTypeType" />
         *     </extension>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Argument
            extends NameValuePairType
        {

            /**
             * The data type of the argument as pertains to the language. Example: "int", "double", "char *".
             * 
             */
            @XmlAttribute(name = "dataType", required = true)
            protected DataTypeType dataType;

            /**
             * The data type of the argument as pertains to the language. Example: "int", "double", "char *".
             * 
             * @return
             *     possible object is
             *     {@link DataTypeType }
             *     
             */
            public DataTypeType getDataType() {
                return dataType;
            }

            /**
             * Sets the value of the dataType property.
             * 
             * @param value
             *     allowed object is
             *     {@link DataTypeType }
             *     
             * @see #getDataType()
             */
            public void setDataType(DataTypeType value) {
                this.dataType = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="sourceName" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}ipxactURI"/>
         *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}fileType"/>
         *       </sequence>
         *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sourceName",
            "fileType"
        })
        public static class SourceFile {

            /**
             * Source file for the boot load.  Relative names are searched for in the project directory and the source of the component directory.
             * 
             */
            @XmlElement(required = true)
            protected IpxactURI sourceName;
            /**
             * Enumerated file types known by IP-XACT.
             * 
             */
            @XmlElement(required = true)
            protected FileType fileType;
            /**
             * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
             * 
             */
            @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;

            /**
             * Source file for the boot load.  Relative names are searched for in the project directory and the source of the component directory.
             * 
             * @return
             *     possible object is
             *     {@link IpxactURI }
             *     
             */
            public IpxactURI getSourceName() {
                return sourceName;
            }

            /**
             * Sets the value of the sourceName property.
             * 
             * @param value
             *     allowed object is
             *     {@link IpxactURI }
             *     
             * @see #getSourceName()
             */
            public void setSourceName(IpxactURI value) {
                this.sourceName = value;
            }

            /**
             * Enumerated file types known by IP-XACT.
             * 
             * @return
             *     possible object is
             *     {@link FileType }
             *     
             */
            public FileType getFileType() {
                return fileType;
            }

            /**
             * Sets the value of the fileType property.
             * 
             * @param value
             *     allowed object is
             *     {@link FileType }
             *     
             * @see #getFileType()
             */
            public void setFileType(FileType value) {
                this.fileType = value;
            }

            /**
             * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getId()
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>Name">
     *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Group {

        @XmlValue
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "Name")
        protected String value;
        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         */
        @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getId()
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
