//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ieee.ipxact.v2022;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <group ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}fieldReferenceGroup"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addressSpaceRef",
    "memoryMapRef",
    "memoryRemapRef",
    "bankRef",
    "addressBlockRef",
    "registerFileRef",
    "registerRef",
    "alternateRegisterRef",
    "fieldRef"
})
@XmlRootElement(name = "indirectAddressRef")
public class IndirectAddressRef {

    protected IndirectAddressRef.AddressSpaceRef addressSpaceRef;
    protected IndirectAddressRef.MemoryMapRef memoryMapRef;
    protected MemoryRemapRef memoryRemapRef;
    protected List<BankRef> bankRef;
    protected AddressBlockRef addressBlockRef;
    protected List<RegisterFileRef> registerFileRef;
    protected RegisterRef registerRef;
    protected AlternateRegisterRef alternateRegisterRef;
    @XmlElement(required = true)
    protected FieldRef fieldRef;

    /**
     * Gets the value of the addressSpaceRef property.
     * 
     * @return
     *     possible object is
     *     {@link IndirectAddressRef.AddressSpaceRef }
     *     
     */
    public IndirectAddressRef.AddressSpaceRef getAddressSpaceRef() {
        return addressSpaceRef;
    }

    /**
     * Sets the value of the addressSpaceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndirectAddressRef.AddressSpaceRef }
     *     
     */
    public void setAddressSpaceRef(IndirectAddressRef.AddressSpaceRef value) {
        this.addressSpaceRef = value;
    }

    /**
     * Gets the value of the memoryMapRef property.
     * 
     * @return
     *     possible object is
     *     {@link IndirectAddressRef.MemoryMapRef }
     *     
     */
    public IndirectAddressRef.MemoryMapRef getMemoryMapRef() {
        return memoryMapRef;
    }

    /**
     * Sets the value of the memoryMapRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndirectAddressRef.MemoryMapRef }
     *     
     */
    public void setMemoryMapRef(IndirectAddressRef.MemoryMapRef value) {
        this.memoryMapRef = value;
    }

    /**
     * Gets the value of the memoryRemapRef property.
     * 
     * @return
     *     possible object is
     *     {@link MemoryRemapRef }
     *     
     */
    public MemoryRemapRef getMemoryRemapRef() {
        return memoryRemapRef;
    }

    /**
     * Sets the value of the memoryRemapRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemoryRemapRef }
     *     
     */
    public void setMemoryRemapRef(MemoryRemapRef value) {
        this.memoryRemapRef = value;
    }

    /**
     * Gets the value of the bankRef property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankRef property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getBankRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BankRef }
     * </p>
     * 
     * 
     * @return
     *     The value of the bankRef property.
     */
    public List<BankRef> getBankRef() {
        if (bankRef == null) {
            bankRef = new ArrayList<>();
        }
        return this.bankRef;
    }

    /**
     * Gets the value of the addressBlockRef property.
     * 
     * @return
     *     possible object is
     *     {@link AddressBlockRef }
     *     
     */
    public AddressBlockRef getAddressBlockRef() {
        return addressBlockRef;
    }

    /**
     * Sets the value of the addressBlockRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressBlockRef }
     *     
     */
    public void setAddressBlockRef(AddressBlockRef value) {
        this.addressBlockRef = value;
    }

    /**
     * Gets the value of the registerFileRef property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the registerFileRef property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getRegisterFileRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegisterFileRef }
     * </p>
     * 
     * 
     * @return
     *     The value of the registerFileRef property.
     */
    public List<RegisterFileRef> getRegisterFileRef() {
        if (registerFileRef == null) {
            registerFileRef = new ArrayList<>();
        }
        return this.registerFileRef;
    }

    /**
     * Gets the value of the registerRef property.
     * 
     * @return
     *     possible object is
     *     {@link RegisterRef }
     *     
     */
    public RegisterRef getRegisterRef() {
        return registerRef;
    }

    /**
     * Sets the value of the registerRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisterRef }
     *     
     */
    public void setRegisterRef(RegisterRef value) {
        this.registerRef = value;
    }

    /**
     * Gets the value of the alternateRegisterRef property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateRegisterRef }
     *     
     */
    public AlternateRegisterRef getAlternateRegisterRef() {
        return alternateRegisterRef;
    }

    /**
     * Sets the value of the alternateRegisterRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateRegisterRef }
     *     
     */
    public void setAlternateRegisterRef(AlternateRegisterRef value) {
        this.alternateRegisterRef = value;
    }

    /**
     * Gets the value of the fieldRef property.
     * 
     * @return
     *     possible object is
     *     {@link FieldRef }
     *     
     */
    public FieldRef getFieldRef() {
        return fieldRef;
    }

    /**
     * Sets the value of the fieldRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldRef }
     *     
     */
    public void setFieldRef(FieldRef value) {
        this.fieldRef = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <attribute name="addressSpaceRef" use="required" type="{http://www.w3.org/2001/XMLSchema}Name" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AddressSpaceRef {

        @XmlAttribute(name = "addressSpaceRef", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "Name")
        protected String addressSpaceRef;

        /**
         * Gets the value of the addressSpaceRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressSpaceRef() {
            return addressSpaceRef;
        }

        /**
         * Sets the value of the addressSpaceRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressSpaceRef(String value) {
            this.addressSpaceRef = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <attribute name="memoryMapRef" use="required" type="{http://www.w3.org/2001/XMLSchema}Name" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MemoryMapRef {

        @XmlAttribute(name = "memoryMapRef", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "Name")
        protected String memoryMapRef;

        /**
         * Gets the value of the memoryMapRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemoryMapRef() {
            return memoryMapRef;
        }

        /**
         * Sets the value of the memoryMapRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemoryMapRef(String value) {
            this.memoryMapRef = value;
        }

    }

}
