//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ieee.ipxact.v2022;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}stringExpression"/>
 *         <element name="commandLineSwitch" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}stringExpression"/>
 *         <element name="enable" type="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}unsignedBitExpression"/>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}generatorRef" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}vendorExtensions" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}id.att"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "commandLineSwitch",
    "enable",
    "generatorRef",
    "vendorExtensions"
})
@XmlRootElement(name = "linkerCommandFile")
public class LinkerCommandFile {

    /**
     * Linker command file name.
     * 
     */
    @XmlElement(required = true)
    protected StringExpression name;
    /**
     * The command line switch to specify the linker command file.
     * 
     */
    @XmlElement(required = true)
    protected StringExpression commandLineSwitch;
    /**
     * Specifies whether to generate and enable the linker command file.
     * 
     */
    @XmlElement(required = true)
    protected UnsignedBitExpression enable;
    /**
     * A reference to a generator element.
     * 
     */
    protected List<GeneratorRef> generatorRef;
    /**
     * Container for vendor specific extensions.
     * 
     */
    protected VendorExtensions vendorExtensions;
    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     */
    @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Linker command file name.
     * 
     * @return
     *     possible object is
     *     {@link StringExpression }
     *     
     */
    public StringExpression getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringExpression }
     *     
     * @see #getName()
     */
    public void setName(StringExpression value) {
        this.name = value;
    }

    /**
     * The command line switch to specify the linker command file.
     * 
     * @return
     *     possible object is
     *     {@link StringExpression }
     *     
     */
    public StringExpression getCommandLineSwitch() {
        return commandLineSwitch;
    }

    /**
     * Sets the value of the commandLineSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringExpression }
     *     
     * @see #getCommandLineSwitch()
     */
    public void setCommandLineSwitch(StringExpression value) {
        this.commandLineSwitch = value;
    }

    /**
     * Specifies whether to generate and enable the linker command file.
     * 
     * @return
     *     possible object is
     *     {@link UnsignedBitExpression }
     *     
     */
    public UnsignedBitExpression getEnable() {
        return enable;
    }

    /**
     * Sets the value of the enable property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedBitExpression }
     *     
     * @see #getEnable()
     */
    public void setEnable(UnsignedBitExpression value) {
        this.enable = value;
    }

    /**
     * A reference to a generator element.
     * 
     * Gets the value of the generatorRef property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the generatorRef property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getGeneratorRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeneratorRef }
     * </p>
     * 
     * 
     * @return
     *     The value of the generatorRef property.
     */
    public List<GeneratorRef> getGeneratorRef() {
        if (generatorRef == null) {
            generatorRef = new ArrayList<>();
        }
        return this.generatorRef;
    }

    /**
     * Container for vendor specific extensions.
     * 
     * @return
     *     possible object is
     *     {@link VendorExtensions }
     *     
     */
    public VendorExtensions getVendorExtensions() {
        return vendorExtensions;
    }

    /**
     * Sets the value of the vendorExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorExtensions }
     *     
     * @see #getVendorExtensions()
     */
    public void setVendorExtensions(VendorExtensions value) {
        this.vendorExtensions = value;
    }

    /**
     * A generic mechanism for annotating elements with unique identifiers. See: http://www.w3.org/TR/xml-id/ for more information.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getId()
     */
    public void setId(String value) {
        this.id = value;
    }

}
