//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ieee.ipxact.v2022;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}left"/>
 *         <element ref="{http://www.accellera.org/XMLSchema/IPXACT/1685-2022}right"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "left",
    "right"
})
@XmlRootElement(name = "range")
public class Range {

    /**
     * The optional element left specifies the left boundary.
     * 
     */
    @XmlElement(required = true)
    protected UnsignedIntExpression left;
    /**
     * The optional element right specifies the right boundary.
     * 
     */
    @XmlElement(required = true)
    protected UnsignedIntExpression right;

    /**
     * The optional element left specifies the left boundary.
     * 
     * @return
     *     possible object is
     *     {@link UnsignedIntExpression }
     *     
     */
    public UnsignedIntExpression getLeft() {
        return left;
    }

    /**
     * Sets the value of the left property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedIntExpression }
     *     
     * @see #getLeft()
     */
    public void setLeft(UnsignedIntExpression value) {
        this.left = value;
    }

    /**
     * The optional element right specifies the right boundary.
     * 
     * @return
     *     possible object is
     *     {@link UnsignedIntExpression }
     *     
     */
    public UnsignedIntExpression getRight() {
        return right;
    }

    /**
     * Sets the value of the right property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedIntExpression }
     *     
     * @see #getRight()
     */
    public void setRight(UnsignedIntExpression value) {
        this.right = value;
    }

}
